### ISSUE TITLE
simulate() not working

### ISSUE THREAD

**Issue by kwootton** [PoisotLab/BioEnergeticFoodWebs.jl#55] opened 2018-07-16 20:20 UTC
## Expected behavior
I'm trying to follow the steps for "First simulation" outlined in the manual. 
- 

## Actual behavior
I can get the foodweb (A), I get a warning when I run model_parameters(A), but it works (see warning below). simulate() doesn't work at all. First I think it doesn't like the option for steps, but even when I remove that I still get an error (see below).

------------------
Warning when I try and run model_parameters(A):

WARNING: !(B::BitArray) is deprecated, use .!(B) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] !(::BitArray{1}) at .\deprecated.jl:57
 [3] make_parameters(::Dict{Symbol,Any}) at C:\Users\kewo0002\.julia\v0.6\BioEnergeticFoodWebs\src\.\make_parameters.jl:190
 [4] #model_parameters#17(::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Symbol, ::Array{Float64,1}, ::Array{Bool,1}, ::BioEnergeticFoodWebs.#model_parameters, ::Array{Int64,2}) at C:\Users\kewo0002\.julia\v0.6\BioEnergeticFoodWebs\src\.\make_parameters.jl:92
 [5] model_parameters(::Array{Int64,2}) at C:\Users\kewo0002\.julia\v0.6\BioEnergeticFoodWebs\src\.\make_parameters.jl:61
 [6] eval(::Module, ::Any) at .\boot.jl:235
 [7] eval_user_input(::Any, ::Base.REPL.REPLBackend) at .\REPL.jl:66
 [8] macro expansion at .\REPL.jl:97 [inlined]
 [9] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at .\event.jl:73
while loading no file, in expression starting on line 0
----------------------

Error when running > s = simulate(p, b, start=0, stop=500):

ERROR: MethodError: no method matching (::BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}})(::Array{Float64,1}, ::Void, ::Float64)
Closest candidates are:
  f(::Any, ::Any) at C:\Users\kewo0002\.julia\v0.6\BioEnergeticFoodWebs\src\.\simulate.jl:44
Stacktrace:
[1] ode_determine_initdt(::Array{Float64,1}, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::DiffEqBase.#ODE_DEFAULT_NORM, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Void,BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.ODEIntegrator{OrdinaryDiffEq.Rodas4{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType},Array{Float64,1},Float64,Void,Float64,Float64,Float64,Array{Array{Float64,1},1},DiffEqBase.ODESolution{Float64,2,Array{Array{Float64,1},1},Void,Void,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Void,BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.Rodas4{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType},OrdinaryDiffEq.InterpolationData{BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Rodas4ConstantCache{DiffEqDiffTools.TimeDerivativeWrapper{BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Array{Float64,1},Void},DiffEqDiffTools.UDerivativeWrapper{BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Float64,Void},OrdinaryDiffEq.RodasConstantCache{Float64,Float64}}}},BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,OrdinaryDiffEq.Rodas4ConstantCache{DiffEqDiffTools.TimeDerivativeWrapper{BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Array{Float64,1},Void},DiffEqDiffTools.UDerivativeWrapper{BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Float64,Void},OrdinaryDiffEq.RodasConstantCache{Float64,Float64}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,DiffEqBase.#ODE_DEFAULT_NORM,DiffEqBase.CallbackSet{Tuple{},Tuple{}},DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN,DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE,DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK,DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Void,Void,Int64,Array{Float64,1},Array{Float64,1},Array{Float64,1}},Array{Float64,1}}) at C:\Users\kewo0002\.julia\v0.6\OrdinaryDiffEq\src\initdt.jl:126
[2] auto_dt_reset! at C:\Users\kewo0002\.julia\v0.6\OrdinaryDiffEq\src\integrators\integrator_interface.jl:250 [inlined]
[3] #init#1470(::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Void, ::Bool, ::Bool, ::Bool, ::Bool, ::Void, ::Bool, ::Bool, ::Float64, ::Bool, ::Rational{Int64}, ::Void, ::Void, ::Int64, ::Rational{Int64}, ::Int64, ::Rational{Int64}, ::Rational{Int64}, ::Bool, ::Int64, ::Void, ::Void, ::Int64, ::Float64, ::Float64, ::DiffEqBase.#ODE_DEFAULT_NORM, ::DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN, ::DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::String, ::DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE, ::Void, ::Bool, ::Bool, ::Array{Any,1}, ::DiffEqBase.#init, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Void,BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.Rodas4{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType}, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at C:\Users\kewo0002\.julia\v0.6\OrdinaryDiffEq\src\solve.jl:320
[4] (::DiffEqBase.#kw##init)(::Array{Any,1}, ::DiffEqBase.#init, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Void,BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.Rodas4{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType}, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at .\<missing>:0
[5] #solve#1469(::Array{Any,1}, ::Function, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Void,BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.Rodas4{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType}, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at C:\Users\kewo0002\.julia\v0.6\OrdinaryDiffEq\src\solve.jl:6
[6] (::DiffEqBase.#kw##solve)(::Array{Any,1}, ::DiffEqBase.#solve, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Void,BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.Rodas4{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType}, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at .\<missing>:0 (repeats 2 times)
[7] #solve#2(::Bool, ::Array{Any,1}, ::Function, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Void,BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::Void) at C:\Users\kewo0002\.julia\v0.6\DifferentialEquations\src\default_solve.jl:14
[8] (::DiffEqBase.#kw##solve)(::Array{Any,1}, ::DiffEqBase.#solve, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Void,BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::Void) at .\<missing>:0
[9] #solve#1(::Bool, ::Array{Any,1}, ::Function, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Void,BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}) at C:\Users\kewo0002\.julia\v0.6\DifferentialEquations\src\default_solve.jl:5
[10] (::DiffEqBase.#kw##solve)(::Array{Any,1}, ::DiffEqBase.#solve, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Void,BioEnergeticFoodWebs.#f#28{Dict{Symbol,Any}},Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}) at .\<missing>:0
[11] #simulate#27(::Int64, ::Int64, ::Symbol, ::Function, ::Dict{Symbol,Any}, ::Array{Float64,1}) at C:\Users\kewo0002\.julia\v0.6\BioEnergeticFoodWebs\src\.\simulate.jl:48
[12] simulate(::Dict{Symbol,Any}, ::Array{Float64,1}) at C:\Users\kewo0002\.julia\v0.6\BioEnergeticFoodWebs\src\.\simulate.jl:35

- 

## Steps to reproduce

1. using BioEnergeticFoodWebs
2. A = nichemodel(10, 0.3);
3. p = model_parameters(A);
4. b = rand(size(A, 1));
5. s=simulate(p,b,start=0,stop=50)

## System information

- `julia --version` Version 0.6.4 (2018-07-09 19:09 UTC)
- `Pkg.status("BioEnergeticFoodWebs")`: 0.3.1
- OS and version: Windows 10 Education, version 1703

**Comment by evadelmas** [comment] 2018-07-16 21:16
Hi @kwootton, 

It looks like the warning you are getting when using `model_parameters` is caused by some deprecation that we fixed recently. Maybe try running `Pkg.update()` to fetch those changes. 

I am not able to reproduce the error you are getting when using `simulate` (although, as you noticed, the `steps` keyword is deprecated, we will fix that asap in the docs). I think that updating the package should also fix that problem, the last release introduces a lot of changes and fixes quite a few bugs.

**Comment by ChrisRackauckas** [comment] 2018-07-16 21:32
Yes, the

```julia
Closest candidates are:
f(::Any, ::Any) at C:\Users\kewo0002.julia\v0.6\BioEnergeticFoodWebs\src.\simulate.jl:44
Stacktrace:
```

points to the fact that he's using a version of this package which was before https://github.com/PoisotLab/BioEnergeticFoodWebs.jl/pull/43 since it now uses the `f(u,p,t)` instead of the `f(t,u)`. And indeed if you check the releases you will see

https://github.com/PoisotLab/BioEnergeticFoodWebs.jl/releases

v0.3.1 was March 20th. So the fix for this is to tag a new version. I would recommend setting up Attobot to help with version tagging.

https://github.com/attobot/attobot

**Comment by tpoisot** [comment] 2018-07-16 21:39
@kwootton one way to get a most recent version would be to use `Pkg.clone("BioEnergeticFoodWebs")` -- we are not quite ready to release a new version (@evadelmas and @Azenor and I are working on a bunch of things over the next days), but aim to do so very soon.

**Comment by ChrisRackauckas** [comment] 2018-07-16 21:41
Since it's already installed, use `Pkg.checkout("BioEnergeticFoodWebs")` to get the current master.

**Comment by tpoisot** [comment] 2018-07-16 22:04
Oh right, I always forget about this one.

**Closed as completed** 2019-02-15 17:44 UTC
