### ISSUE TITLE
Problems with Installation

### ISSUE THREAD

**Issue by CleggTom** [PoisotLab/BioEnergeticFoodWebs.jl#12] opened 2017-03-15 15:53 UTC
## Expected behavior
Installation of the package

## Actual behavior
Julia returns an error stating:
`unsatisfiable package requirements detected: no feasible version could be found for package: ChunkedArrays`

after this package is installed and the BEFW package is installed again it returns the same error as above for the following packages:

`Parameters
ResettableStacks
DataStructures
Iterators`

After this it finally allows installation.
 

## Steps to reproduce

1.Start with clean install of Julia 0.5.1
2.Run `Pkg.add("BioEnergeticFoodWebs")`
3.Add the packages that are returned by the error

## System information

- `julia 0.5.1`
- `Pkg.status("BioEnergeticFoodWebs")` - NA
- `OSX 10.10.5`

**Comment by tpoisot** [comment] 2017-03-15 17:14
`ChunkedArrays` are not required by `BioEnergeticFoodWebs` -- so the problem may be with another package, or one of the dependencies.

When you run `Pkg.status("BioEnergeticFoodWebs")`, do you see `0.3.0`?

**Comment by CleggTom** [comment] 2017-03-15 17:22
yep after installing all the packages listed above i now have   `0.3.0`.

I'm now running into a problem when I load the package telling me it has failed to precompile the StochasticDiffEq module. I assume this is all due to the switching to the new differential equation solver

**Comment by tpoisot** [comment] 2017-03-15 17:41
This is actually an issue in `StochasticDiffEq`: JuliaDiffEq/StochasticDiffEq.jl#16 -- it should be solved soon.

You can temporarily work using `0.2.0` with

~~~ julia
Pkg.pin("BioEnergeticFoodWebs", v"0.2.0")
~~~

when this will be fixed, just go through

~~~ julia
Pkg.free("BioEnergeticFoodWebs")
Pkg.update()
~~~

**Closed as completed by tpoisot** 2017-03-15 17:41 UTC
Labels: bug

**Comment by tpoisot** [comment] 2017-03-15 18:22
@TomClegg94 The issue is in `Parameters.jl`, and it should be temporarily fixed in a few hours.

**Comment by ChrisRackauckas** [comment] 2017-03-16 09:17
This should be fixed now. Sorry for the wait!

**Comment by CleggTom** [comment] 2017-03-16 11:26
The package is all working now and i'm on version `0.3.0`. 

However, in order to get the new version I re-added the package `Pkg.add("BioEnergeticFoodWebs")` with a clean install of Julia and got the same error as outlined in the first post (Julia wont install `BioEnergeticFoodWebs` until all those other packages are manually installed)

**Comment by tpoisot** [comment] 2017-03-16 13:40
@TomClegg94 I'm unable to reproduce. How did you install Julia?

**Comment by CleggTom** [comment] 2017-03-16 13:46
I used the .dmg on julialang.org. I also use the Juno IDE on atom.

**Comment by tpoisot** [comment] 2017-03-16 13:54
OK -- I see nothing in the code here that could trigger this error, and I'm unable to reproduce.

**Comment by ChrisRackauckas** [comment] 2017-03-16 15:29
@TomClegg94 can you post your Pkg.status()? Pinned packages can sometimes do this.
